site_name: k8s101
repo_url: https://github.com/masci/k8s101
docs_dir: src
site_dir: docs
edit_uri: tree/master/src
nav:
  - Home: index.md
  - Course units:
    - 010-first-contact.md
    - 020-pods.md
    - 030-declarative.md
    - 040-labels.md
    - 050-annotations.md
    - 060-deployments.md
    - 070-services.md
    - 080-ingress.md
    - 090-configmaps.md
    - 100-secrets.md
    - 110-helm.md
